Add version detail
AngkorGroup/VolvoCashClient pull request #15
Opened 2020-11-05 21:54 UTC by AlonsoArellano25

#### Contexto
Se añadió la versión de la aplicación

- Se cerro el https://github.com/AngkorGroup/VolvoCashClient/issues/12#issue-737160579

#### Notas

| ios | android | 
| --- | ------  |
|  -  |    -    |

2020-11-05 22:06 UTC, jjercx requested changes

2020-11-05 22:06 UTC, jjercx commented on src/screens/auth/LoginScreen.tsx
> +    color:"#fff"
los colores los tengo en el tema, asi que si algun dia quieren nuevos colores ("una nueva version de blanco") los podemos cambiar solo en una parte y no tener que buscarlo por todo el codigo

2020-11-05 22:06 UTC, jjercx commented on src/screens/auth/LoginScreen.tsx
> +            <Text style={styles.text}>v 1.0.1</Text>
esta genial, pero creo que podemos mejorarlo:
1. que sea "v1.0.1", sin espacio
2. debe depender del sistema operativo, recuerda que las versiones varian entre android y iOS.
3. tengo un archivo con las constantes en la carpeta utils, ahi deberiamos tener un ANDROID_VERSION y IOS_VERSION

2020-11-05 22:25 UTC, AlonsoArellano25 commented on src/screens/auth/LoginScreen.tsx
> +            <Text style={styles.text}>v 1.0.1</Text>
Qué valores iniciales tendrán estas constantes? o para IOS y Android les pongo v1.0.1?

2020-11-06 00:34 UTC, jjercx requested changes
Te deje unos cambios. Tambien hay un error en el Sonar, corrige eso tambien porfa

2020-11-06 00:34 UTC, jjercx commented on src/screens/auth/LoginScreen.tsx
> +             :<Text style={styles.text}>{ANDROID_VERSION}</Text> }
aqui no estas usando la version de iOS

2020-11-06 00:34 UTC, jjercx commented on src/screens/auth/LoginScreen.tsx
> +             :<Text style={styles.text}>{ANDROID_VERSION}</Text> }
tambien podrias hacerlo mas conciso si haces el if dentro del `Text`

```suggestion
             <Text style={styles.text}>{Platform.OS=== "android" ? ANDROID_VERSION : IOS_VERSION }</Text>
```

2020-11-06 00:34 UTC, jjercx commented on src/screens/auth/LoginScreen.tsx
> +    ...theme.primaryOverDark
aca hay una regla de convenciones del proyecto que deberias usar coma al final de los JSON
```suggestion
    ...theme.primaryOverDark,
```
Que editor usas? El proyecto usa TSLint y Prettier, asegurate de configurarlos en tu editor. Con VSCode hay extensiones y videos de youtube o articulos de medium que explican como configurarlo

2020-11-10 00:59 UTC, merged