Add badge in tab icon
AngkorGroup/VolvoCashClient pull request #20
Opened 2020-11-19 21:26 UTC by AlonsoArellano25

#### Contexto
Se añadió un badge para el icono del tab de pagos pendientes.

#### Notas

| ios | android | 
| --- | ![iconwithbadge](https://user-images.githubusercontent.com/56784425/99725748-28df5100-2a7b-11eb-9e7a-0fd1be75c660.png) |
|  -  |    -    |

2020-11-19 21:44 UTC, jjercx requested changes

2020-11-19 21:44 UTC, jjercx commented on src/components/tab/IconWithBadge.tsx
> +export default function IconWithBadge({ name, badgeCount, size }: any) {
hay que crear una interfaz para los Props y no usar any

2020-11-19 21:44 UTC, jjercx commented on src/components/tab/IconWithBadge.tsx
> +        <View style={{ width: size * 1.5, height: size * 1 }}>
tranformar a constante

2020-11-19 21:44 UTC, jjercx commented on src/components/tab/IconWithBadge.tsx
> +            <Img source={name} style={{ width: unit(37), height: unit(30) }} />
mover al objeto styles

2020-11-19 21:44 UTC, jjercx commented on src/components/tab/IconWithBadge.tsx
> +})
Lo ideal es terminal los archivos con cambios de linea y con puntos y comas si son cosas de JS.

te paso mis config de vscode quiza te ayudan:
```
"files.trimTrailingWhitespace": true,
  "files.eol": "\n",
  "files.trimFinalNewlines": true,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
```

2020-11-19 21:44 UTC, jjercx commented on src/screens/main/MainNavigation.tsx
> +  const items = chargeList.length;
mejorar el nombre, quiza `chargeCount`

2020-11-20 15:31 UTC, jjercx commented on src/components/tab/IconWithBadge.tsx
> +    const styleBadge = { width: size * 1.5, height: size * 1 }
una ventaja de tenerlo asi separado, a parte de la legibilidad, es que podrias usar `useMemo`. Es parecido a `useCallback` pero para valores. Asi cada vez que entre componente, el styleBadge no se va a tener que recalcular, solo se recalcularia si size cambiara, en este caso no es necesario, pero en propyectos mas complejos mejroas de performance asi pueden ser mas sinficativas

2020-11-20 15:31 UTC, jjercx approved these changes

2020-11-20 15:38 UTC, AlonsoArellano25 commented on src/components/tab/IconWithBadge.tsx
> +    const styleBadge = { width: size * 1.5, height: size * 1 }
Entiendo, gracias por la recomendación.

2020-11-20 18:45 UTC, jjercx requested changes

2020-11-20 18:45 UTC, jjercx commented on src/utils/constants.ts
> +export const ANDROID_VERSION = 'v1.2.5 (8)';
aca no solo tienes que cambiar la version, sino tambien el build number (el numero entre parentesis). igual en el gradle, no veo ese cambio

2020-11-25 21:20 UTC, merged